# Generated by Django 5.0 on 2024-06-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comparison_graph",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("Inception", models.CharField(max_length=10, null=True)),
                ("EfficientNet", models.CharField(max_length=10, null=True)),
                ("Hybrid", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "Comparisongraph",
            },
        ),
        migrations.CreateModel(
            name="EfficientNet_model",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=10)),
                ("model_executed", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "EfficientNet_model",
            },
        ),
        migrations.CreateModel(
            name="Hybrid_model",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=10)),
                ("model_executed", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "Hybrid_model",
            },
        ),
        migrations.CreateModel(
            name="InceptionV3_model",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("model_accuracy", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=10)),
                ("model_executed", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "InceptionV3_model",
            },
        ),
        migrations.CreateModel(
            name="Train_test_split_model",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("Images_training", models.CharField(max_length=10, null=True)),
                ("Images_validation", models.CharField(max_length=10, null=True)),
                ("Images_classes", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "Traintestsplit",
            },
        ),
    ]
