# Generated by Django 5.0 on 2024-06-21 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0002_comparison_graph_efficientnet_model_hybrid_model_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InceptionV3_model",
        ),
    ]
