# Generated by Django 5.0 on 2024-06-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0003_delete_inceptionv3_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="InceptionV3_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, unique=True)),
                ("model_accuracy", models.CharField(max_length=100)),
                ("model_executed", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "InceptionV3_model",
            },
        ),
    ]
