# Generated by Django 5.0 on 2024-06-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adminapp", "0005_delete_comparison_graph_delete_dataset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comparison_graph",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("Inception", models.CharField(max_length=10, null=True)),
                ("EfficientNet", models.CharField(max_length=10, null=True)),
                ("Hybrid", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "Comparisongraph",
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="datasets/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dataset_table",
            },
        ),
        migrations.CreateModel(
            name="EfficientNet_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, unique=True)),
                ("model_accuracy", models.CharField(max_length=100)),
                ("model_executed", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "EfficientNet_model",
            },
        ),
        migrations.CreateModel(
            name="Hybrid_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, unique=True)),
                ("model_accuracy", models.CharField(max_length=100)),
                ("model_executed", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Hybrid_model",
            },
        ),
        migrations.CreateModel(
            name="InceptionV3_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, unique=True)),
                ("model_accuracy", models.CharField(max_length=100)),
                ("model_executed", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "InceptionV3_model",
            },
        ),
        migrations.CreateModel(
            name="Train_test_split_model",
            fields=[
                ("S_No", models.AutoField(primary_key=True, serialize=False)),
                ("Images_training", models.CharField(max_length=10, null=True)),
                ("Images_validation", models.CharField(max_length=10, null=True)),
                ("Images_classes", models.CharField(max_length=10, null=True)),
            ],
            options={
                "db_table": "Traintestsplit",
            },
        ),
    ]
