# Generated by Django 5.0 on 2024-06-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0006_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="graph_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fake_details", models.CharField(max_length=100)),
                ("Real_details", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "graph_model",
            },
        ),
    ]
